version: '3.9'
services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: Flask_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"